name: Build Windows

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: Windows-2019

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup dependencies
        run: |
          choco install -y git
          choco install -y visualstudio2019buildtools
          choco install -y godot

      - name: Build game
        run: |
          godot --export "Windows Desktop" LabAdventure.exe
          ls

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: game_windows
          path: LabAdventure.exe

