name: Build Godot project on Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Godot
      run: |
        Invoke-WebRequest -Uri "https://downloads.tuxfamily.org/godotengine/3.2.3/mono/Godot_v3.2.3-stable_mono_win64.zip" -OutFile "Godot.zip"
        Expand-Archive Godot.zip -DestinationPath godot
        Set-Item -Path Env:GODOT_MONO -Value "${{ env.GITHUB_WORKSPACE }}/godot/Godot_v3.2.3-stable_mono_win64.exe"
    - name: Build project
      run: |
        & "$env:GODOT_MONO" --export "Windows Desktop" project.godot
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyProject
        path: project.exe
