name: Build Windows

on:
  push:
    branches:
      - main

env:
  matrix:
    - OS: Windows-2019

steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Setup dependencies
    run: |
      choco install -y git
      choco install -y visualstudio2019buildtools
      choco install -y godot

  - name: Build game
    run: |
      cd godot_project
      godot --export "Windows Desktop" game.exe

  - name: Upload artifact
    uses: actions/upload-artifact@v2
    with:
      name: game_windows
      path: godot_project/game.exe

